CREATE_TABLE = ("CREATE TABLE user ("
                "id integer PRIMARY KEY, "
                "email varchar(300), "
                "password varchar(300), "
                "full_name varchar(300), "
                "price_per_hour integer,"
                "city varchar(300))")
INSERT_VALUES = (
    "INSERT INTO user"
    "('id','email', 'password', 'full_name', 'price_per_hour', 'city') VALUES "
    "(1,'novlu@mail.com', 'mkdXjIjYM', 'Людмила Новикова', 500, 'Санкт-Петербург'),"
    "(2,'tripper678@yahhaa.com', 'eGGPtRKS5', 'Андрей Васечкин', 700, 'Москва'),"
    "(3,'georgiberidze@mail.com', 'NWRV0Z9ZC', 'Георги Беридзе', 300, 'Тбилиси'),"
    "(4,'oksi.laslas89@mail.com', 'TenhtQOjv', 'Оксана Ласкина', 800, 'Казань'),"
    "(5,'vanyahot888@inmail.com', '5YGRPtYlw', 'Иван Горячий', 400, 'Сочи'),"
    "(6,'yanaturkiy@mail.com', 'rN3HI4elT', 'Яна Ивлева', 1500, 'Стамбул'),"
    "(7,'irafromrome@yahhaa.com', 'mWmSmkNsD', 'Ирина Самидзе', 1200, 'Рим'),"
    "(8,'pskovstalker@mail.com', 'M572gH5lG', 'Владислав Ванькин', 900, 'Псков'),"
    "(9,'dinadina13@mail.com', 'v2dSbgPYb', 'Дина Левинова', 800, 'Хельсинки'),"
    "(10,'mark.loud@mail.com', 'pz4ZIYu1l', 'Марк Звонкий', 1700, 'Нижний Новгород')")
